package com.orfiplus.model;
// Generated 29/08/2016 10:16:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Orden generated by hbm2java
 */
public class Orden  implements java.io.Serializable {


     private int idOrden;
     private Personas personas;
     private Date fechaEntrega;
     private Date fechaOrden;
     private Boolean estadoinfo;

    public Orden() {
    }

	
    public Orden(int idOrden) {
        this.idOrden = idOrden;
    }
    public Orden(int idOrden, Personas personas, Date fechaEntrega, Date fechaOrden, Boolean estadoinfo) {
       this.idOrden = idOrden;
       this.personas = personas;
       this.fechaEntrega = fechaEntrega;
       this.fechaOrden = fechaOrden;
       this.estadoinfo = estadoinfo;
    }
   
    public int getIdOrden() {
        return this.idOrden;
    }
    
    public void setIdOrden(int idOrden) {
        this.idOrden = idOrden;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Date getFechaOrden() {
        return this.fechaOrden;
    }
    
    public void setFechaOrden(Date fechaOrden) {
        this.fechaOrden = fechaOrden;
    }
    public Boolean getEstadoinfo() {
        return this.estadoinfo;
    }
    
    public void setEstadoinfo(Boolean estadoinfo) {
        this.estadoinfo = estadoinfo;
    }




}


