package com.orfiplus.model;
// Generated 29/08/2016 10:16:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private int idPersonas;
     private String nombres;
     private String apellidos;
     private String correoe;
     private String password;
     private Integer telefonos;
     private Boolean estadoinfo;
     private Date fechaCreacion;
     private Set<Orden> ordens = new HashSet<Orden>(0);

    public Personas() {
    }

	
    public Personas(int idPersonas) {
        this.idPersonas = idPersonas;
    }
    public Personas(int idPersonas, String nombres, String apellidos, String correoe, String password, Integer telefonos, Boolean estadoinfo, Date fechaCreacion, Set<Orden> ordens) {
       this.idPersonas = idPersonas;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.correoe = correoe;
       this.password = password;
       this.telefonos = telefonos;
       this.estadoinfo = estadoinfo;
       this.fechaCreacion = fechaCreacion;
       this.ordens = ordens;
    }
   
    public int getIdPersonas() {
        return this.idPersonas;
    }
    
    public void setIdPersonas(int idPersonas) {
        this.idPersonas = idPersonas;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreoe() {
        return this.correoe;
    }
    
    public void setCorreoe(String correoe) {
        this.correoe = correoe;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Integer telefonos) {
        this.telefonos = telefonos;
    }
    public Boolean getEstadoinfo() {
        return this.estadoinfo;
    }
    
    public void setEstadoinfo(Boolean estadoinfo) {
        this.estadoinfo = estadoinfo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set<Orden> getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set<Orden> ordens) {
        this.ordens = ordens;
    }




}


